### ISSUE TITLE
add function to change variable type

### ISSUE THREAD

**Issue by leethargo** [leethargo/CSIP#13]
For MathProgBase, we need to set the variable types after the variables were added with `loadproblem!`. This can probably be done with `SCIPchgVarType` in the problem stage.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/MathProgBase.jl/issues/40
I'm not really in favor of changing the MathProgBase interface at this point though, doesn't seem necessary.

**Comment by leethargo** [comment]
I was also considering to have a lazy implementation of `loadproblem!` that only stores the matrix and waits for a call to `setvartype!` and then do the changes just prior to solve. But this sounds too complicated for a first implementation.

**Comment by mlubin** [comment]
That's also very reasonable
