### ISSUE TITLE
Add all methods needed for SCIP.jl

### ISSUE THREAD

**Issue by leethargo** [leethargo/CSIP#18]
We want to use CSIP in [SCIP.jl](https://github.com/leethargo/SCIP.jl) and implement the `LinearQuadraticModel` interface of `MathProgBase`. The current functionality of CSIP is not sufficient and needs to be extended.

- [x] allow callbacks to stop solving with status "user limit" (d95e449)

**Comment by fserra** [comment]
what else is missing here?

**Comment by leethargo** [comment]
There's user cuts, and some "getters" and "setters" for model updates, e.g. changing LHS/RHS of constraints. I'm not sure whether they are actually needed.

**Comment by leethargo** [comment]
Also, for the future (of SCIP itself), incomplete solution candidates.

**Comment by leethargo** [comment]
We already have separate issues for most of these.
