### ISSUE TITLE
add heuristic callbacks

### ISSUE THREAD

**Issue by mlubin** [leethargo/CSIP#3]

**Comment by leethargo** [comment]
Let's split up heuristics and user cuts. I'll be working on heuristics first.

I'm not familiar with heuristic callbacks in the major solvers, but from my experience with SCIP, there's typically three different "locations" where a heuristic might be applied:

- before the actual solving starts (construction heuristics)
- after the LP is solved in every node (rounding heuristics etc.)
- after some solutions was found (improving heuristics, local search)

Should we support all of these use cases?

**Comment by mlubin** [comment]
Why are callbacks needed for before the solve starts? Shouldn't the user
just provide the best known starting point?

For the other two cases I'd say there should be a single callback where we
gove some information about the current state and users can choose to run
their heuristic or not.
On Jun 13, 2016 17:40, "Robert Schwarz" <notifications@github.com> wrote:

Let's split up heuristics and user cuts. I'll be working on heuristics
first.

I'm not familiar with heuristic callbacks in the major solvers, but from my
experience with SCIP, there's typically three different "locations" where a
heuristic might be applied:

   - before the actual solving starts (construction heuristics)
   - after the LP is solved in every node (rounding heuristics etc.)
   - after some solutions was found (improving heuristics, local search)

Should we support all of these use cases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/leethargo/CSIP/issues/3#issuecomment-225701627>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABp0M4271nn3XEPmw76_K4QO4I5qylgkks5qLcBQgaJpZM4Izzoo>
.

**Comment by leethargo** [comment]
Good point, setting the initial values. The difference between the other two situations is that the solution available to the solution is known to be feasible, or not (LP relaxation).

**Comment by mlubin** [comment]
Ok, what about a single heuristic callback that lets the user know if the solution came from an LP relaxation or from a feasible solution?

**Comment by leethargo** [comment]
Yes, that's what I was thinking, too.

**Comment by leethargo** [comment]
I thought that we could distinguish the two cases easily with some `HEUR_TIMING`
in SCIP. But in fact, we'd probably have to catch some `EVENTTYPE_SOLFOUND` in order to be called
whenever an improving solution is discovered. Surprisingly no heuristic implemented in SCIP uses that at the moment.

So, for the first iteration, we only support heuristic callbacks that are called on every MIP node.
