### ISSUE TITLE
Set initial values for variables

### ISSUE THREAD

**Issue by leethargo** [leethargo/CSIP#6]
To give an initial solution, the user might want to give values for (a subset of) the variables.
These should be checked at the beginning of the solve.

I prefer to not change the signature of `CSIPaddVar` and instead provide a new function `CSIPsetInitialValues`, analogous to the bounds.

Also, I'm not sure whether SCIP already supports "partial" solutions, but I believe it's still WIP. In that case, I don't want to implement anything on the CSIP side now, but just try to pass the (0-filled?) values as a full solution candidate.

See also the discussion about heuristic callbacks in #3.

**Comment by mlubin** [comment]
Agreed it should be a separate function. The input could be a single flat
vector with NaN entries for unspecified values. This is the format we use
in MathProgBase.

**Comment by leethargo** [comment]
So there will be a heuristic plugin in the next SCIP release (or now, on the master branch) that supports "partial solutions". We would then be able to call `SCIPcreatePartialSol` and the subtree below the fixations will be searched with some limits.

In the current release, only full solutions are supported.

**Comment by mlubin** [comment]
Can you call ``SCIPcreatePartialSol`` during the solve also?

**Comment by leethargo** [comment]
No, according to the docs, it's only possible in the `PROBLEM` stage.
